steps:
  - read: project_name
    from: git.remote_name
    fallback:
      prompt: What is the name of the project?
      default:
        from: path.rootdir

  - update: README.md
  - update: package.json
  - update: .env
  - update: .github/workflows/Test.yml