steps:
  - read: project_name
    from: git.remote_name
    fallback:
      prompt: What is the name of the project?
      default:
        from: path.rootdir

  - read: database_type
    prompt: What database type do you want to use?
    choices:
      - MongoDB:
        steps:
          - read: database_var
            eval: "const database = new MongoPersistence(readDatabase, {\n\tsample: new SampleSchema(),\n});"
            remove: src/dAOs/sampleDAO.ts
          - read: database_import
            eval: "import SampleSchema from './schemas/sampleSchema';"
          - read: database_sql
            eval: ""
          - eval: 'MongoDB'
      - PGSQL:
        steps:
        - read: database_var
          eval: "const database = new DAOPersistence(sql, {\n\tsample: new SampleDAO(),\n});"
          remove: src/schemas/sampleSchema.ts
        - read: database_import
          eval: "import { PGSQL } from '@flexiblepersistence/pgsql';\nimport SampleDAO from './dAOs/sampleDAO';"
        - read: database_sql
          eval: "const sql = new PGSQL(readDatabase);"
        - eval: 'PGSQL'
      - MSSQL:
        steps:
        - read: database_var
          eval: "const database = new DAOPersistence(sql, {\n\tsample: new SampleDAO(),\n});"
          remove: src/schemas/sampleSchema.ts
        - read: database_import
          eval: "import { MSSQL } from '@flexiblepersistence/mssql';\nimport SampleDAO from './dAOs/sampleDAO';"
        - read: database_sql
          eval: "const sql = new MSSQL(readDatabase);"
        - eval: 'MSSQL'

  - update: README.md
  - update: package.json
  - update: .env
  - update: .github/workflows/Test.yml
  - update: src/dBHandler.ts