steps:
  - read: project_name
    from: git.remote_name
    fallback:
      prompt: What is the name of the project?
      default:
        from: path.rootdir

  - read: database_type
    prompt: What database type do you want to use?
    choices:
      - MongoDB:
          steps:
            - read: database_var
              eval: "const database = new MongoPersistence(readDatabase, {\n\tsample: new SampleSchema(),\n});"
            - read: database_import
              eval: "import SampleSchema from './schemas/sampleSchema';"
            - read: database_sql
              eval: "\b"
            - read: database_port
              eval: "27017"
            - read: database_name
              eval: ""
            - read: database_user
              eval: ""
            - read: database_password
              eval: ""
            - read: database_encryption_disabled
              eval: ""
            - remove: src/dAOs/sampleDAO.ts
            - remove: src/dAOs
            - eval: 'MongoDB'
      - PGSQL:
          steps:
          - read: database_var
            eval: "const database = new DAOPersistence(sql, {\n\tsample: new SampleDAO(),\n});"
          - read: database_import
            eval: "import { PGSQL } from '@flexiblepersistence/pgsql';\nimport SampleDAO from './dAOs/sampleDAO';"
          - read: database_sql
            eval: "const sql = new PGSQL(readDatabase);"
          - read: database_port
            eval: "5432"
          - read: database_name
            eval: "db"
          - read: database_user
            eval: "sa"
          - read: database_password
            eval: "Passw@rd"
          - read: database_encryption_disabled
            eval: ""
          - remove: src/schemas/sampleSchema.ts
          - remove: src/schemas
          - eval: 'PGSQL'
      - MSSQL:
          steps:
          - read: database_var
            eval: "const database = new DAOPersistence(sql, {\n\tsample: new SampleDAO(),\n});"
          - read: database_import
            eval: "import { MSSQL } from '@flexiblepersistence/mssql';\nimport SampleDAO from './dAOs/sampleDAO';"
          - read: database_sql
            eval: "const sql = new MSSQL(readDatabase);"
          - read: database_port
            eval: "1433"
          - read: database_name
            eval: "db"
          - read: database_user
            eval: "sa"
          - read: database_password
            eval: "Passw@rd"
          - read: database_encryption_disabled
            eval: "true"
          - remove: src/schemas/sampleSchema.ts
          - remove: src/schemas
          - eval: 'MSSQL'

  - read: framework
    prompt: What rest framework do you want to use?
    choices:
      - express
      - aws-lambda
      - next

  - update: README.md
  - update: package.json
  - update: .env
  - update: .github/workflows/Test.yml
  - update: src/dBHandler.ts