services:

  writeDB:
    image: mongo:latest
    ports:
      - 27017:27015
    environment:
      MONGO_INITDB_ROOT_USERNAME: {{ tmplr.database_user }}
      MONGO_INITDB_ROOT_PASSWORD: {{ tmplr.database_password }}
      MONGO_INITDB_DATABASE: {{ tmplr.database_name }}

  readDB:
    image: {{ tmplr.database_image }}:latest
    ports:
      - {{ tmplr.database_port }}:{{ tmplr.database_port }}
    environment:
      ACCEPT_EULA: Y
      {{ tmplr.database_env_name }}: {{ tmplr.database_user }}
      {{ tmplr.database_env_password }}: {{ tmplr.database_password }}
      {{ tmplr.database_env_database }}: {{ tmplr.database_name }}
