services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  # mssql:
  #   image: "mcr.microsoft.com/mssql/server:latest"
  #   ports:
  #   - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: Passw@rd

  # msminion:
  #   image: mcr.microsoft.com/mssql-tools:latest
  #   depends_on:
  #   - mssql
  #   command: >
  #     sh -c "
  #     echo 'START' &&
  #     echo sleep 60 &&
  #     /opt/mssql-tools/bin/sqlcmd -S mssql -U SA -P 'Passw@rd'
  #     -Q 'USE master
  #     GO
  #     IF NOT EXISTS (SELECT [name]
  #     FROM sys.databases
  #     WHERE [name] = N'db')
  #     CREATE DATABASE db
  #     GO
  #     ' &&
  #     echo 'END'
  #     "

  mssql:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    ports:
    - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw@rd
      MSSQL_DB: db

  pgsql:
    image: "postgres:latest"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Passw@rd
      POSTGRES_USER: sa
      POSTGRES_DB: db